// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWA-7tmcuCREUhqS-IEMERotOPptOHaQc',
    appId: '1:24928634207:web:92c0e1e38eee2bff5122ea',
    messagingSenderId: '24928634207',
    projectId: 'shopeasy-c6db6',
    authDomain: 'shopeasy-c6db6.firebaseapp.com',
    storageBucket: 'shopeasy-c6db6.firebasestorage.app',
    measurementId: 'G-8B1F2NQSXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-bQR-pPAWgGUBVWJvY2g-8bxjBfTtpM',
    appId: '1:24928634207:android:9e211b6e193621465122ea',
    messagingSenderId: '24928634207',
    projectId: 'shopeasy-c6db6',
    storageBucket: 'shopeasy-c6db6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKhN9sIsIKmvYjsvwMdMw_nrX-jOceSHU',
    appId: '1:24928634207:ios:a0e095a44b60da785122ea',
    messagingSenderId: '24928634207',
    projectId: 'shopeasy-c6db6',
    storageBucket: 'shopeasy-c6db6.firebasestorage.app',
    iosBundleId: 'com.example.shopEasy',
  );
}
